title: ROK Monster OCR
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
search.heading_level: 3

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
