title: ROK Monster OCR
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"