title: ROK OCR
remote_theme: pmarsceill/just-the-docs
# theme: "just-the-docs"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"